#!/usr/bin/env python3
"""Regenerate STARS.md from the owner's public GitHub Lists.

Source of truth: the Lists on https://github.com/<user>?tab=stars, read through
the GraphQL API with the `gh` CLI (read-only query, no token ever handled here).
Only public lists and public repositories are written out.

    scripts/update_stars.py            # rewrite STARS.md if the content changed
    scripts/update_stars.py --check    # exit 1 if STARS.md is out of date

Needs `gh auth login` as the list owner: the lists belong to the user, so the
workflow GITHUB_TOKEN cannot read them and this cannot run in Actions.
Standard library only.
"""

from __future__ import annotations

import argparse
import datetime
import json
import re
import subprocess
import sys
from pathlib import Path

DEFAULT_OUTPUT = Path(__file__).resolve().parent.parent / "STARS.md"
SNAPSHOT_PREFIX = "> Snapshot of "

ITEM_FIELDS = """
  pageInfo { hasNextPage endCursor }
  nodes {
    ... on Repository {
      nameWithOwner url description isPrivate
      primaryLanguage { name }
    }
  }
"""

LISTS_QUERY = """
query {
  viewer {
    login
    lists(first: 50) {
      pageInfo { hasNextPage }
      nodes { id name slug description isPrivate items(first: 100) { %s } }
    }
  }
}
""" % ITEM_FIELDS

# Follow-up pages for a list with more than 100 items, addressed by node id so
# the cursor is only ever used against the list it came from.
LIST_ITEMS_QUERY = """
query($id: ID!, $cursor: String) {
  node(id: $id) { ... on UserList { items(first: 100, after: $cursor) { %s } } }
}
""" % ITEM_FIELDS

URL_RE = re.compile(r"https?://[^\s<>]+")
MD_SPECIAL_RE = re.compile(r"([\\|*_\[\]`~])")


def gh_graphql(query: str, **variables: str) -> dict:
    cmd = ["gh", "api", "graphql", "-f", f"query={query}"]
    for key, value in variables.items():
        cmd += ["-f", f"{key}={value}"]
    proc = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
    if proc.returncode != 0:
        sys.exit(f"gh api graphql failed: {proc.stderr.strip() or proc.stdout.strip()}")
    payload = json.loads(proc.stdout)
    if payload.get("errors"):
        sys.exit(f"GraphQL errors: {payload['errors']}")
    return payload["data"]


def fetch_lists() -> tuple[str, list[dict]]:
    """Return (login, public lists) with every public repository, paged fully."""
    data = gh_graphql(LISTS_QUERY)["viewer"]
    if data["lists"]["pageInfo"]["hasNextPage"]:
        sys.exit("More than 50 lists: extend fetch_lists() before trusting the output.")

    result = []
    for lst in data["lists"]["nodes"]:
        if lst["isPrivate"]:
            continue
        items = list(lst["items"]["nodes"])
        page = lst["items"]["pageInfo"]
        while page["hasNextPage"]:
            more = gh_graphql(LIST_ITEMS_QUERY, id=lst["id"], cursor=page["endCursor"])
            items += more["node"]["items"]["nodes"]
            page = more["node"]["items"]["pageInfo"]
        repos = [i for i in items if i and i.get("nameWithOwner") and not i["isPrivate"]]
        repos.sort(key=lambda r: r["nameWithOwner"].lower())
        result.append({**lst, "repos": repos})
    return data["login"], result


def md_text(text: str) -> str:
    """Make third-party text safe inside a table cell: no HTML, no markdown, no pipes."""
    text = " ".join((text or "").split())
    out, pos = [], 0
    for match in URL_RE.finditer(text):
        out.append(escape_plain(text[pos:match.start()]))
        url = match.group(0).rstrip(".,;:!?)")
        out.append(f"<{url}>")
        pos = match.start() + len(url)
    out.append(escape_plain(text[pos:]))
    return "".join(out).strip() or "—"


def escape_plain(text: str) -> str:
    return MD_SPECIAL_RE.sub(r"\\\1", text.replace("<", "&lt;").replace(">", "&gt;"))


def render(login: str, lists: list[dict], today: str) -> str:
    total = sum(len(lst["repos"]) for lst in lists)
    out = [
        "# ⭐ Starred Repositories",
        "",
        f"{total} repositories that `@{login}` has sorted into public",
        f"[GitHub Lists](https://github.com/{login}?tab=stars), grouped by list.",
        "Repositories starred but not yet in a list are not shown.",
        "",
        f"{SNAPSHOT_PREFIX}{today}, generated by `scripts/update_stars.py`. Do not edit by hand.",
        "",
        "## 📌 Quick Navigation",
        "",
    ]
    for lst in lists:
        desc = f" — {md_text(lst['description'])}" if lst["description"] else ""
        out.append(f"- [{md_text(lst['name'])} ({len(lst['repos'])})](#{lst['slug']}){desc}")
    out += ["", "---", ""]

    for lst in lists:
        out += [f'<a id="{lst["slug"]}"></a>', "", f"## {md_text(lst['name'])} ({len(lst['repos'])})", ""]
        if lst["description"]:
            out += [md_text(lst["description"]), ""]
        out += ["| Repository | Language | Description |", "| :--- | :---: | :--- |"]
        for repo in lst["repos"]:
            lang = (repo.get("primaryLanguage") or {}).get("name")
            out.append(
                f"| [{md_text(repo['nameWithOwner'])}]({repo['url']}) "
                f"| {f'`{lang}`' if lang else '—'} | {md_text(repo['description'])} |"
            )
        out.append("")
    return "\n".join(out).rstrip("\n") + "\n"


def strip_snapshot(text: str) -> str:
    return "\n".join(l for l in text.splitlines() if not l.startswith(SNAPSHOT_PREFIX))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--check", action="store_true", help="exit 1 if the file is out of date")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    login, lists = fetch_lists()
    today = datetime.date.today().isoformat()
    new = render(login, lists, today)
    old = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
    same = strip_snapshot(new) == strip_snapshot(old)

    if args.check:
        print("STARS.md is up to date." if same else "STARS.md is out of date: run scripts/update_stars.py")
        return 0 if same else 1
    if same:
        print("STARS.md already up to date, not rewritten.")
        return 0
    args.output.write_text(new, encoding="utf-8")
    print(f"Wrote {args.output} ({sum(len(l['repos']) for l in lists)} repositories in {len(lists)} lists).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
